export const MESSAGE_CREATE = "MESSAGE_CREATE"
export const MESSAGE_UPDATE = "MESSAGE_UPDATE"
export const MESSAGE_DELETE = "MESSAGE_DELETE"

export const CHANNEL_CREATE = "CHANNEL_CREATE"
export const CHANNEL_UPDATE = "CHANNEL_UPDATE"
export const CHANNEL_DELETE = "CHANNEL_DELETE"

export const USER_CREATE = "USER_CREATE"
export const USER_UPDATE = "USER_UPDATE"
export const USER_DELETE = "USER_DELETE"
